server:
  port: 8080  


spring:
  datasource:
    url: jdbc:h2:file:c:/h2/data
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        generate_statistics: false
  h2:
    console:
      enabled: true
      path: /h2
      

logging:
  level:
    com.yk: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    
  
 
